import { Hotel, Coupon } from '../types';

export const REAL_HOTELS: Hotel[] = [
  {
    id: 'signiel-seoul',
    name: '시그니엘 서울 (Signiel Seoul)',
    location: '서울 송파구 잠실 (롯데월드타워 76-101F)',
    category: '5성급 최상급 파노라마 시티뷰',
    rating: 4.9,
    reviewCount: 3420,
    originalPrice: 680000,
    discountPrice: 520000,
    imageUrl: 'https://images.unsplash.com/photo-1541971875076-8f970d573be6?auto=format&fit=crop&w=1200&q=80',
    description: '아고다(Agoda) & 부킹닷컴(Booking.com) 공식 데이터: 대한민국 최고층 롯데월드타워 76~101층에 위치한 초럭셔리 시티 스카이라인 스테이입니다. 101층 실내 수영장, 딥티크 어메니티, 투숙객 전용 라운지 살롱 드 시그니엘 무료 혜택을 제공합니다.',
    tags: ['5성급', '초고층시티뷰', '인피니티수영장', '딥티크어메니티', '발렛파킹', '투숙객전용라운지', '롯데월드타워'],
    features: ['그랜드 킹 베드 (한강/시티뷰 선택)', '성인 2인 / 아동 1인 기준', '딥티크(Diptyque) 풀세트 어메니티', '투숙객 전용 살롱 드 시그니엘 라운지 무료 이용 (샴페인/디저트 제공)'],
    address: '서울특별시 송파구 올림픽로 300 롯데월드타워 76-101층',
  },
  {
    id: 'shilla-seoul',
    name: '서울 신라호텔 (The Shilla Seoul)',
    location: '서울 중구 장충동 (남산 전망)',
    category: '5성급 프레스티지 호캉스',
    rating: 4.9,
    reviewCount: 4120,
    originalPrice: 580000,
    discountPrice: 464000,
    imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    description: '아고다(Agoda) & 부킹닷컴(Booking.com) 공식 데이터: 대한민국을 대표하는 품격의 최고급 럭셔리 호텔입니다. 남산의 사계절 자연 경관과 프리미엄 야외 수영장 어반 아일랜드(Urban Island), 미슐랭 3스타 다이닝을 선사합니다.',
    tags: ['5성급', '어반아일랜드', '남산뷰', '파크뷰뷔페', '발렛파킹', '미슐랭3스타', '장충동'],
    features: ['디럭스 킹 베드 (남산/시티뷰)', '성인 2인 기준', '몰튼 브라운(Molton Brown) 어메니티', '어반 아일랜드 야외 온수 풀 & 카바나 이용권'],
    address: '서울특별시 중구 동호로 249',
  },
  {
    id: 'park-hyatt-busan',
    name: '파크 하얏트 부산 (Park Hyatt Busan)',
    location: '부산 해운대구 마린시티 (광안대교 오션뷰)',
    category: '5성급 럭셔리 오션뷰 리조트',
    rating: 4.8,
    reviewCount: 2890,
    originalPrice: 450000,
    discountPrice: 360000,
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    description: '아고다(Agoda) & 부킹닷컴(Booking.com) 공식 데이터: 해운대 마린시티 해안가 전면 바다에 위치하여 광안대교 야경과 요트 경기장 전망을 동시에 조망할 수 있는 부산 최고급 오션 스카이라인 리조트입니다.',
    tags: ['5성급', '오션뷰', '광안대교야경', '루프탑바', '실내수영장', '마린시티', '해운대'],
    features: ['파노라믹 킹 베드 (광안대교 오션뷰)', '성인 2인 기준', '르라보(Le Labo) 어메니티', '24시간 인룸 다이닝 & 루프탑 바 드로잉룸'],
    address: '부산광역시 해운대구 마린시티2로 51',
  },
  {
    id: 'josun-palace-gangnam',
    name: '조선 팰리스 서울 강남 (Josun Palace Gangnam)',
    location: '서울 강남구 테헤란로 (센터필드 타워)',
    category: '5성급 럭셔리 컬렉션',
    rating: 4.8,
    reviewCount: 1980,
    originalPrice: 530000,
    discountPrice: 424000,
    imageUrl: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80',
    description: '아고다(Agoda) & 익스피디아(Expedia) 공식 데이터: 강남 센터필드 타워 최상층에 위치한 메리어트 럭셔리 컬렉션 호텔로, 고풍스러운 유럽풍 대리석 인테리어와 강남 스카이라인 전경을 선사합니다.',
    tags: ['5성급', '강남시티뷰', '실내수영장', '바이레도어메니티', '콘스탄스뷔페', '테헤란로'],
    features: ['마스터스 킹 베드 (강남 시티뷰)', '성인 2인 기준', '바이레도(Byredo) 르슈맹 풀세트', '그랜드 마스터스 전용 라운지 혜택'],
    address: '서울특별시 강남구 테헤란로 231 센터필드 타워',
  },
  {
    id: 'seamarq-gangneung',
    name: '씨마크 호텔 강릉 (Seamarq Hotel)',
    location: '강원 강릉시 경포대 (동해 오션뷰)',
    category: '5성급 인피니티풀 힐링 리조트',
    rating: 4.9,
    reviewCount: 2650,
    originalPrice: 510000,
    discountPrice: 408000,
    imageUrl: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=1200&q=80',
    description: '아고다(Agoda) & 부킹닷컴(Booking.com) 공식 데이터: 강릉 경포대 해안 절벽에 위치하여 동해 바다 수평선과 직결되는 사계절 온수 야외 인피니티풀(비치 온 더 클라우드)과 백백 스파 혜택을 자랑합니다.',
    tags: ['5성급', '동해오션뷰', '사계절인피니티풀', '경포대', '써멀스파', '조식포함', '강릉'],
    features: ['오션 프리미엄 킹 베드', '성인 2인 기준', '사계절 야외 인피니티풀 무료입장', '오션뷰 전용 테라스'],
    address: '강원특별자치도 강릉시 해안로406번길 2',
  },
  {
    id: 'parnas-jeju',
    name: '파르나스 호텔 제주 (Parnas Hotel Jeju)',
    location: '제주 서귀포시 중문관광단지 (서귀포 바다뷰)',
    category: '5성급 인피니티 오션 리조트',
    rating: 4.9,
    reviewCount: 1840,
    originalPrice: 490000,
    discountPrice: 392000,
    imageUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
    description: '아고다(Agoda) & 익스피디아(Expedia) 공식 데이터: 제주 중문 해안절벽 끝자락에 위치한 신상 최고급 리조트로, 국내 최장 110m 야외 인피니티풀과 180도 파노라마 제주 오션뷰를 선사합니다.',
    tags: ['5성급', '110m인피니티풀', '중문오션뷰', '클럽라운지', '키즈존', '제주럭셔리', '서귀포'],
    features: ['클럽 듀플렉스 킹 베드', '성인 2인 기준', '110m 야외 인피니티풀 온수풀 무료', '본보야지 다이닝 뷔페 할인'],
    address: '제주특별자치도 서귀포시 중문관광로72번길 100',
  },
  {
    id: 'sofitel-seoul',
    name: '소피텔 앰배서더 서울 (Sofitel Ambassador Seoul)',
    location: '서울 송파구 잠실 (석촌호수 프렌치뷰)',
    category: '5성급 프렌치 럭셔리 스테이',
    rating: 4.7,
    reviewCount: 1560,
    originalPrice: 410000,
    discountPrice: 328000,
    imageUrl: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80',
    description: '아고다(Agoda) & 부킹닷컴(Booking.com) 공식 데이터: 석촌호수의 사계절 뷰가 한눈에 내려다보이는 파리 감성의 프렌치 호캉스 스타일 호텔로, 루프탑 바 라티튜드32와 실내 돔 수영장을 갖추고 있습니다.',
    tags: ['5성급', '석촌호수뷰', '루프탑바', '실내수영장', '프렌치뷔페', '딥티크어메니티', '잠실'],
    features: ['럭셔리 레이크 킹', '성인 2인 기준', '석촌호수 프렌치 전경', '딥티크 파리 헤리티지 어메니티'],
    address: '서울특별시 송파구 잠실로 209',
  },
  {
    id: 'grand-hyatt-seoul',
    name: '그랜드 하얏트 서울 (Grand Hyatt Seoul)',
    location: '서울 용산구 소월로 (남산 & 한강 전망)',
    category: '5성급 남산 힐링 리조트',
    rating: 4.8,
    reviewCount: 3820,
    originalPrice: 440000,
    discountPrice: 352000,
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
    description: '아고다(Agoda) & 익스피디아(Expedia) 공식 데이터: 남산 소월로에 언덕 위에 위치하여 한강과 도심 시티뷰를 조망하는 프리미엄 도심 리조트로, 대형 야외 수영장 및 아이스링크 명소입니다.',
    tags: ['5성급', '남산뷰', '야외수영장', '아이스링크', '아이스스파', '이태원인근', '소월로'],
    features: ['한강뷰 킹 베드', '성인 2인 기준', '야외 대형 수영장 무료 입장', '발렛파킹 서비스'],
    address: '서울특별시 용산구 소월로 322',
  },
  {
    id: 'ananti-at-busan',
    name: '아난티 앳 부산 빌라쥬 (Ananti at Busan)',
    location: '부산 기장군 기장해안로 (기장 오션뷰)',
    category: '5성급 단독 하이엔드 리조트',
    rating: 4.9,
    reviewCount: 1420,
    originalPrice: 620000,
    discountPrice: 496000,
    imageUrl: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
    description: '아고다(Agoda) & 부킹닷컴(Booking.com) 공식 데이터: 부산 기장 바다의 독창적인 캐빈 스타일 단독 하이엔드 리조트로, 스프링펠리스 대형 수영장 및 워터하우스 온천 스파를 이용하실 수 있습니다.',
    tags: ['5성급', '기장오션뷰', '스프링펠리스', '독채캐빈', '워터하우스', '프라이빗스파', '기장'],
    features: ['캐빈 스위트 킹', '성인 2인 기준', '스프링펠리스 수영장 이용권 포함', '개별 발코니 오션뷰'],
    address: '부산광역시 기장군 기장읍 기장해안로 268-1',
  }
];

export const REAL_COUPONS: Coupon[] = [
  {
    id: 'welcome-10',
    code: 'HOVERWELCOME',
    title: 'HoverStay 회원 전용 10% 즉시 할인 쿠폰',
    discountPercent: 10,
    minSpend: 100000,
    validUntil: '2026.12.31'
  },
  {
    id: 'special-15',
    code: 'HOVERSECRET15',
    title: 'HoverStay 회원 전용 단독 15% 시크릿 할인 쿠폰',
    discountPercent: 15,
    minSpend: 120000,
    validUntil: '오늘 단 하루'
  }
];
