import { Hotel, Coupon } from '../types';

export const MOCK_HOTELS: Hotel[] = [
  {
    id: 'grand-walkerhill',
    name: '그랜드 워커힐 서울',
    location: '서울 광진구 (아차산 & 한강뷰)',
    category: '5성급 힐링 리조트',
    rating: 4.8,
    reviewCount: 1240,
    originalPrice: 320000,
    discountPrice: 248000,
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
    description: '아차산 자락에 위치하여 한강 전경이 탁 트인 서울 도심 속 최고급 힐링 리조트입니다. 실내 인피니티 수영장과 정갈한 프리미엄 뷔페 레스토랑을 갖추고 있습니다.',
    tags: ['5성급', '한강뷰', '실내수영장', '럭셔리스파', '무료주차'],
    features: ['킹 베드 1개', '성인 2인 기준', '조식 포함 옵션', '무료 Wi-Fi'],
    address: '서울특별시 광진구 워커힐로 177',
  },
  {
    id: 'signiel-seoul',
    name: '시그니엘 서울',
    location: '서울 송파구 잠실 (롯데월드타워)',
    category: '5성급 럭셔리 시티뷰',
    rating: 4.9,
    reviewCount: 2310,
    originalPrice: 650000,
    discountPrice: 520000,
    imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80',
    description: '국내 최고층 롯데월드타워 76~101층에 위치하여 서울의 파노라마 시티뷰를 조망할 수 있는 최상급 프리미엄 호텔입니다.',
    tags: ['5성급', '초고층시티뷰', '실내수영장', '에스프레소머신', '발렛파킹'],
    features: ['그랜드 킹 베드', '성인 2인 기준', '딥티크 어메니티', '라운지 무료 이용'],
    address: '서울특별시 송파구 올림픽로 300 롯데월드타워 76-101층',
  },
  {
    id: 'park-hyatt-busan',
    name: '파크 하얏트 부산',
    location: '부산 해운대구 (마린시티 광안대교뷰)',
    category: '5성급 오션뷰 리조트',
    rating: 4.8,
    reviewCount: 1850,
    originalPrice: 420000,
    discountPrice: 336000,
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    description: '해운대 마린시티에 위치하여 광안대교의 환상적인 야경과 전면 유리창 너머 탁 트인 부산 바다 전망을 선사하는 럭셔리 스테이입니다.',
    tags: ['5성급', '오션뷰', '광안대교야경', '루프탑바', '실내수영장'],
    features: ['킹 베드 1개', '성인 2인 기준', '오션뷰 욕조', '24시간 룸서비스'],
    address: '부산광역시 해운대구 마린시티2로 51',
  },
  {
    id: 'bukchon-hanok',
    name: '북촌 한옥 스테이 락고재',
    location: '서울 종로구 (북촌한옥마을)',
    category: '전통 프리미엄 한옥독채',
    rating: 4.9,
    reviewCount: 680,
    originalPrice: 380000,
    discountPrice: 298000,
    imageUrl: 'https://images.unsplash.com/photo-1584467541268-b040f83be3fd?auto=format&fit=crop&w=1200&q=80',
    description: '100년 역사를 간직한 고즈넉한 북촌 한옥마을 내 위치한 단독 프라이빗 스테이입니다. 전통 기와 지붕과 정갈한 마당, 다도 프로그램을 함께 제공합니다.',
    tags: ['독채', '전통한옥', '프라이빗정원', '황토찜질방', '조식제공'],
    features: ['전통 다도 세트', '성인 2인 기준', '정갈한 한식 조식', '무료 다도 체험'],
    address: '서울특별시 종로구 계동길 49-23',
  },
  {
    id: 'seamarq-gangneung',
    name: '씨마크 호텔 강릉',
    location: '강원 강릉시 (경포대 오션뷰)',
    category: '5성급 인피니티풀 리조트',
    rating: 4.9,
    reviewCount: 1540,
    originalPrice: 480000,
    discountPrice: 384000,
    imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    description: '동해 바다와 수평선이 이어지는 야외 인피니티풀을 보유한 강릉 최상급 오션뷰 럭셔리 리조트입니다.',
    tags: ['5성급', '오션뷰', '인피니티풀', '조식뷔페', '사우나'],
    features: ['오션뷰 킹 베드', '성인 2인 기준', '인피니티풀 무료입장', '발코니 보유'],
    address: '강원특별자치도 강릉시 해안로406번길 2',
  },
  {
    id: 'sofitel-seoul',
    name: '소피텔 앰배서더 서울',
    location: '서울 송파구 (석촌호수뷰)',
    category: '5성급 럭셔리 프렌치',
    rating: 4.7,
    reviewCount: 920,
    originalPrice: 390000,
    discountPrice: 312000,
    imageUrl: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80',
    description: '석촌호수가 내려다보이는 프렌치 럭셔리 호텔로, 감각적인 루프탑 라운지 바와 프렌치 정찬을 즐길 수 있습니다.',
    tags: ['5성급', '석촌호수뷰', '루프탑바', '실내수영장', '프렌치뷔페'],
    features: ['프리미엄 킹 베드', '성인 2인 기준', '석촌호수 전망', '딥티크 어메니티'],
    address: '서울특별시 송파구 잠실로 209',
  }
];

export const MOCK_COUPONS: Coupon[] = [
  {
    id: 'welcome-10',
    code: 'HOVERWELCOME',
    title: 'HoverStay 회원 전용 10% 즉시 할인 쿠폰',
    discountPercent: 10,
    minSpend: 100000,
    validUntil: '2026.12.31'
  },
  {
    id: 'special-15',
    code: 'HOVERSECRET15',
    title: 'HoverStay 회원 전용 단독 15% 시크릿 할인 쿠폰',
    discountPercent: 15,
    minSpend: 120000,
    validUntil: '오늘 단 하루'
  }
];
