import { Hotel, Coupon } from '../types';

export const MOCK_HOTELS: Hotel[] = [
  {
    id: 'signiel-seoul',
    name: '시그니엘 서울 (Signiel Seoul)',
    location: '서울 송파구 잠실 (롯데월드타워 76-101F)',
    category: '5성급 최상급 파노라마 시티뷰',
    rating: 4.9,
    reviewCount: 3420,
    originalPrice: 680000,
    discountPrice: 520000,
    imageUrl: 'http://localhost:5001/api/proxy-image?url=' + encodeURIComponent('https://pix6.agoda.net/hotelImages/1530939/-1/c1d9b3d077c449339e72aa689e4b6eb0.jpg'),
    description: '국내 최고층 롯데월드타워 76~101층에 위치하여 서울의 파노라마 시티뷰 및 한강 전망을 전면 조망할 수 있는 아시아 최고급 프리미엄 럭셔리 스테이입니다. (아고다 실시간 파이프라인 연동)',
    tags: ['5성급', '초고층시티뷰', '인피니티수영장', '딥티크어메니티', '발렛파킹', '투숙객전용라운지'],
    features: ['그랜드 킹 베드', '성인 2인 기준', '딥티크 풀세트 어메니티', '투숙객 전용 살롱 드 시그니엘 무료 이용'],
    address: '서울특별시 송파구 올림픽로 300 롯데월드타워 76-101층',
  },
  {
    id: 'shilla-seoul',
    name: '서울 신라호텔 (The Shilla Seoul)',
    location: '서울 중구 장충동 (남산 전망)',
    category: '5성급 프레스티지 호캉스',
    rating: 4.9,
    reviewCount: 4120,
    originalPrice: 580000,
    discountPrice: 464000,
    imageUrl: 'http://localhost:5001/api/proxy-image?url=' + encodeURIComponent('https://pix6.agoda.net/hotelImages/10609/-1/a2444dfbcf627ea0bcf885600c7bc698.jpg'),
    description: '한국을 대표하는 전통과 품격의 프리미엄 호텔로, 남산의 수려한 자연과 야외 수영장 어반 아일랜드(Urban Island)에서 최상의 휴식을 선사합니다. (아고다 실시간 파이프라인 연동)',
    tags: ['5성급', '어반아일랜드', '남산뷰', '파크뷰뷔페', '발렛파킹', '미슐랭3스타'],
    features: ['디럭스 킹 베드', '성인 2인 기준', '몰튼 브라운 어메니티', '어반 아일랜드 야외수영장 혜택'],
    address: '서울특별시 중구 동호로 249',
  },
  {
    id: 'park-hyatt-busan',
    name: '파크 하얏트 부산 (Park Hyatt Busan)',
    location: '부산 해운대구 마린시티 (광안대교 오션뷰)',
    category: '5성급 럭셔리 오션뷰 리조트',
    rating: 4.8,
    reviewCount: 2890,
    originalPrice: 450000,
    discountPrice: 360000,
    imageUrl: 'http://localhost:5001/api/proxy-image?url=' + encodeURIComponent('https://pix6.agoda.net/hotelImages/410884/-1/2c0d8df30aa24c4314e304918e7d23d8.jpg'),
    description: '해운대 마린시티에 위치하여 광안대교의 환상적인 야경과 전면 유리창 너머 탁 트인 부산 바다 전망을 선사하는 아시아 최고의 럭셔리 해변 스테이입니다. (아고다 실시간 파이프라인 연동)',
    tags: ['5성급', '오션뷰', '광안대교야경', '루프탑바', '실내수영장', '마린시티'],
    features: ['파노라믹 킹 베드', '성인 2인 기준', '르라보 어메니티', '24시간 룸서비스'],
    address: '부산광역시 해운대구 마린시티2로 51',
  },
  {
    id: 'josun-palace-gangnam',
    name: '조선 팰리스 서울 강남 (Josun Palace Gangnam)',
    location: '서울 강남구 테헤란로 (센터필드 타워)',
    category: '5성급 럭셔리 컬렉션',
    rating: 4.8,
    reviewCount: 1980,
    originalPrice: 530000,
    discountPrice: 424000,
    imageUrl: 'http://localhost:5001/api/proxy-image?url=' + encodeURIComponent('https://pix6.agoda.net/hotelImages/22896577/-1/6c30e527d72221b65d1d8efd2dd91932.jpg'),
    description: '강남 센터필드 타워 최고층에 위치한 조선호텔앤리조트의 최상위 럭셔리 브랜치로, 고풍스러운 대리석 인테리어와 강남 스카이라인 뷰를 제공합니다. (아고다 실시간 파이프라인 연동)',
    tags: ['5성급', '강남시티뷰', '실내수영장', '바이레도어메니티', '콘스탄스뷔페'],
    features: ['마스터스 킹 베드', '성인 2인 기준', '바이레도 어메니티', '그랜드 마스터스 라운지 혜택'],
    address: '서울특별시 강남구 테헤란로 231 센터필드 타워',
  },
  {
    id: 'seamarq-gangneung',
    name: '씨마크 호텔 강릉 (Seamarq Hotel)',
    location: '강원 강릉시 경포대 (동해 오션뷰)',
    category: '5성급 인피니티풀 힐링 리조트',
    rating: 4.9,
    reviewCount: 2650,
    originalPrice: 510000,
    discountPrice: 408000,
    imageUrl: 'http://localhost:5001/api/proxy-image?url=' + encodeURIComponent('https://pix6.agoda.net/hotelImages/969188/-1/67ef7394c8e7efb0c950d859556aef71.jpg'),
    description: '동해 바다 수평선과 이어지는 사계절 야외 인피니티풀(비치 온 더 클라우드)을 보유한 강릉 경포대 최고급 힐링 럭셔리 스테이입니다. (아고다 실시간 파이프라인 연동)',
    tags: ['5성급', '동해오션뷰', '사계절인피니티풀', '경포대', '써멀스파', '조식포함'],
    features: ['오션 프리미엄 킹 베드', '성인 2인 기준', '인피니티풀 무료입장', '오션뷰 개별 테라스'],
    address: '강원특별자치도 강릉시 해안로406번길 2',
  },
  {
    id: 'parnas-jeju',
    name: '파르나스 호텔 제주 (Parnas Hotel Jeju)',
    location: '제주 서귀포시 중문관광단지 (서귀포 바다뷰)',
    category: '5성급 인피니티 오션 리조트',
    rating: 4.9,
    reviewCount: 1840,
    originalPrice: 490000,
    discountPrice: 392000,
    imageUrl: 'http://localhost:5001/api/proxy-image?url=' + encodeURIComponent('https://pix6.agoda.net/hotelImages/31737409/-1/3c1e2d9b62ec54f7623a856a9089f815.jpg'),
    description: '제주 중문 해안가절벽 바로 앞에 위치하여 국내 최장 110m 인피니티풀과 탁 트인 파노라마 서귀포 오션뷰를 만끽할 수 있는 최신상 럭셔리 리조트입니다. (아고다 실시간 파이프라인 연동)',
    tags: ['5성급', '110m인피니티풀', '중문오션뷰', '클럽라운지', '키즈존', '제주럭셔리'],
    features: ['클럽 듀플렉스 킹', '성인 2인 기준', '110m 야외 인피니티풀 무료', '본보야지 뷔페 조식 할인'],
    address: '제주특별자치도 서귀포시 중문관광로72번길 100',
  },
  {
    id: 'sofitel-seoul',
    name: '소피텔 앰배서더 서울 (Sofitel Ambassador Seoul)',
    location: '서울 송파구 잠실 (석촌호수 프렌치뷰)',
    category: '5성급 프렌치 럭셔리 스테이',
    rating: 4.7,
    reviewCount: 1560,
    originalPrice: 410000,
    discountPrice: 328000,
    imageUrl: 'http://localhost:5001/api/proxy-image?url=' + encodeURIComponent('https://pix6.agoda.net/hotelImages/24701292/-1/59381736b4122d2c18ab934415ad821a.jpg'),
    description: '석촌호수가 한눈에 내려다보이는 프랑스 감성의 럭셔리 호텔로, 루프탑 라운지 라티튜드32와 정통 프렌치 다이닝을 선사합니다. (아고다 실시간 파이프라인 연동)',
    tags: ['5성급', '석촌호수뷰', '루프탑바', '실내수영장', '프렌치뷔페', '딥티크어메니티'],
    features: ['럭셔리 레이크 킹', '성인 2인 기준', '석촌호수 전망', '딥티크 헤리티지 어메니티'],
    address: '서울특별시 송파구 잠실로 209',
  },
  {
    id: 'grand-hyatt-seoul',
    name: '그랜드 하얏트 서울 (Grand Hyatt Seoul)',
    location: '서울 용산구 소월로 (남산 & 한강 전망)',
    category: '5성급 남산 힐링 리조트',
    rating: 4.8,
    reviewCount: 3820,
    originalPrice: 440000,
    discountPrice: 352000,
    imageUrl: 'http://localhost:5001/api/proxy-image?url=' + encodeURIComponent('https://pix6.agoda.net/hotelImages/8908/-1/658bcf7b2b64d39f4efef2aa25fbce87.jpg'),
    description: '남산 자락에 위치하여 서울 도심과 한강을 한눈에 조망할 수 있는 전통의 야외 수영장 및 아이스링크 명소 럭셔리 호텔입니다. (아고다 실시간 파이프라인 연동)',
    tags: ['5성급', '남산뷰', '야외수영장', '아이스링크', '아이스스파', '이태원인근'],
    features: ['한강뷰 킹 베드', '성인 2인 기준', '야외 수영장 무료 입장', '발렛파킹 지원'],
    address: '서울특별시 용산구 소월로 322',
  },
  {
    id: 'ananti-at-busan',
    name: '아난티 앳 부산 빌라쥬 (Ananti at Busan)',
    location: '부산 기장군 기장해안로 (기장 오션뷰)',
    category: '5성급 단독 하이엔드 리조트',
    rating: 4.9,
    reviewCount: 1420,
    originalPrice: 620000,
    discountPrice: 496000,
    imageUrl: 'http://localhost:5001/api/proxy-image?url=' + encodeURIComponent('https://pix6.agoda.net/hotelImages/41846434/-1/e3f4e24ab4b602052c92e9eb90a6e08c.jpg'),
    description: '부산 기장 바다의 광활한 경관을 품은 독창적인 캐빈 스타일의 럭셔리 프라이빗 리조트로, 스프링펠리스 야외 수영장을 보유하고 있습니다. (아고다 실시간 파이프라인 연동)',
    tags: ['5성급', '기장오션뷰', '스프링펠리스', '독채캐빈', '워터하우스', '프라이빗스파'],
    features: ['캐빈 스위트 킹', '성인 2인 기준', '스프링펠리스 수영장 이용권', '프라이빗 발코니'],
    address: '부산광역시 기장군 기장읍 기장해안로 268-1',
  }
];

export const MOCK_COUPONS: Coupon[] = [
  {
    id: 'welcome-10',
    code: 'HOVERWELCOME',
    title: 'HoverStay 회원 전용 10% 즉시 할인 쿠폰',
    discountPercent: 10,
    minSpend: 100000,
    validUntil: '2026.12.31'
  },
  {
    id: 'special-15',
    code: 'HOVERSECRET15',
    title: 'HoverStay 회원 전용 단독 15% 시크릿 할인 쿠폰',
    discountPercent: 15,
    minSpend: 120000,
    validUntil: '오늘 단 하루'
  }
];
